name: Build

on:
  push:
    branches: [ folia-patches ]
  pull_request:
    branches: [ folia-patches ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Action Github"

      - name: Apply patches
        run: |
          chmod +x gradlew 
          ./gradlew applyPatches

      - name: Build
        run: ./gradlew -p Essentials-Patched build --stacktrace -x test -x checkstyleMain --refresh-dependencies --continue

      - name: Archive jars
        uses: actions/upload-artifact@v4
        with:
          name: EssentialsX-Folia jars
          path: Essentials-Patched/jars/

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: build-${{ github.ref_name }}-${{ github.run_number }}
          name: EssentialsX-Folia - ${{ github.run_number }}
          body: |
            This release is automatically compiled by GitHub Actions
            ### Commit Message
            ${{ github.event.head_commit.message }}
          artifacts: Essentials-Patched/jars/*.jar
          generateReleaseNotes: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: false