name: Build

on:
  push:
    branches: ["folia-patches"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Apply patches
        run: ./gradlew applyPatches --no-configuration-cache
      - name: Build
        run: ./gradlew :Essentials-Patched:EssentialsX:shadowJar --no-configuration-cache
      - uses: actions/upload-artifact@v4
        with:
          name: EssentialsX-Folia
          path: Essentials-Patched/Essentials/build/libs/EssentialsX-*.jar
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: EssentialsX Folia Build
          files: Essentials-Patched/Essentials/build/libs/EssentialsX-*.jar
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
